"""AT-7.3 — Controlled FP2 Approval corpus (fp2-reasoning-sparse-1.0.0).

Native Approval records only: loop_decision with approve/reject/modify.
Does NOT modify controlled_batch_2, Planner, or mapping.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from aiodoo_training.system_training_contract.generators.common import (
    fixture_metadata,
    rid,
)
from aiodoo_training.system_training_contract.quality.common import fingerprint_record
from aiodoo_training.system_training_contract.quality.gates import (
    scan_forbidden_how,
    scan_taxonomy,
)
from aiodoo_training.system_training_contract.records import (
    LoopDecisionRecord,
    validate_record_mapping,
)
from aiodoo_training.system_training_contract.version import SYSTEM_TRAINING_CONTRACT_VERSION

REASONING_SPARSE_VERSION: str = "fp2-reasoning-sparse-1.0.0"
APPROVAL_CONTROLLED_GENERATOR: str = "approval_controlled"
TARGET_MIN = 150
TARGET_MAX = 250
TARGET_PREFERRED = 200
MIN_FAMILIES = 50
_APPROVAL_KINDS = frozenset({"approve", "reject", "modify"})


@dataclass(frozen=True)
class _ApprFamily:
    family_id: str
    domain: str | None
    subject: str
    kind_a: str
    reason_a: str
    next_a: str
    kind_b: str
    reason_b: str
    next_b: str


def _families() -> tuple[_ApprFamily, ...]:
    """≥50 scenario families; each yields ~2 related approval loop_decision records."""
    # (slug, domain, subject, kind_a, reason_a, next_a, kind_b, reason_b, next_b)
    specs: list[tuple[str, str | None, str, str, str, str, str, str, str]] = [
        # --- Odoo ---
        (
            "appr_odoo_sale_discount",
            "odoo",
            "sale order exceptional discount",
            "approve",
            "Discount within authorized manager threshold for this customer",
            "Allow confirmation with approved discount",
            "reject",
            "Discount exceeds policy ceiling for the customer segment",
            "Return order for revised pricing without exceptional discount",
        ),
        (
            "appr_odoo_invoice_credit",
            "odoo",
            "customer credit note issuance",
            "approve",
            "Credit note matches documented return and tax evidence",
            "Proceed to post the credit note",
            "modify",
            "Credit amount is correct but tax lines need adjustment",
            "Revise tax lines then resubmit for approval",
        ),
        (
            "appr_odoo_purchase_po",
            "odoo",
            "purchase order above threshold",
            "approve",
            "PO amount and vendor match budgeted purchase request",
            "Confirm purchase order with vendor",
            "reject",
            "Vendor quote is outdated relative to current RFQ",
            "Return PO for refreshed vendor quotation",
        ),
        (
            "appr_odoo_expense_claim",
            "odoo",
            "employee expense claim",
            "approve",
            "Receipt and category match company expense policy",
            "Mark expense claim approved for reimbursement",
            "reject",
            "Receipt missing for claim above receipt-required threshold",
            "Return claim requesting attached receipt",
        ),
        (
            "appr_odoo_leave_request",
            "odoo",
            "employee leave request",
            "approve",
            "Leave balance and team coverage are adequate",
            "Approve leave and notify calendar owners",
            "modify",
            "Dates overlap a critical milestone; shorten the leave window",
            "Propose alternate leave dates for employee confirmation",
        ),
        (
            "appr_odoo_stock_scrap",
            "odoo",
            "inventory scrap of high-value lot",
            "approve",
            "Quality evidence supports scrap of the identified lot",
            "Validate scrap and update inventory valuation",
            "reject",
            "Lot identity on scrap does not match quality report",
            "Return scrap for corrected lot reference",
        ),
        (
            "appr_odoo_payment_batch",
            "odoo",
            "vendor payment batch",
            "approve",
            "Batch totals match open bills and bank availability",
            "Release payment batch to bank",
            "modify",
            "One bill is disputed; remove it from the batch",
            "Resubmit batch without disputed bill",
        ),
        (
            "appr_odoo_access_rights",
            "odoo",
            "elevated accounting access grant",
            "approve",
            "Role change is justified and time-bounded for closing",
            "Grant temporary accounting group membership",
            "reject",
            "Requested groups exceed least-privilege for the stated task",
            "Return access request with reduced group set",
        ),
        (
            "appr_odoo_pricelist_publish",
            "odoo",
            "new customer pricelist publish",
            "approve",
            "Margin checks pass for all published rules",
            "Publish pricelist to target customer segment",
            "modify",
            "Two SKUs fall below margin floor; adjust those rules",
            "Update SKU rules then resubmit publish approval",
        ),
        (
            "appr_odoo_refund_pos",
            "odoo",
            "POS refund above cashier limit",
            "approve",
            "Manager review confirms refund matches original tender",
            "Complete POS refund with manager approval",
            "reject",
            "Refund reason conflicts with no-return promotion terms",
            "Deny refund and keep original POS order",
        ),
        (
            "appr_odoo_mrp_mo_cancel",
            "odoo",
            "manufacturing order cancellation",
            "approve",
            "No consumed components; cancel is safe for capacity plan",
            "Cancel manufacturing order and free capacity",
            "modify",
            "Partial consumption exists; cancel only remaining ops",
            "Amend cancel scope to unfinished operations only",
        ),
        (
            "appr_odoo_crm_won_exception",
            "odoo",
            "CRM opportunity won with margin exception",
            "approve",
            "Strategic account exception is documented by sales director",
            "Mark opportunity won under approved exception",
            "reject",
            "Margin exception lacks director authorization evidence",
            "Keep opportunity open pending authorization",
        ),
        (
            "appr_odoo_bank_statement",
            "odoo",
            "bank statement force-reconcile",
            "approve",
            "Difference is within write-off tolerance and explained",
            "Force-reconcile statement line with write-off",
            "reject",
            "Difference exceeds write-off tolerance without explanation",
            "Return statement line for investigation",
        ),
        (
            "appr_odoo_vendor_bill",
            "odoo",
            "vendor bill without PO match",
            "approve",
            "Non-PO bill is covered by standing service agreement",
            "Post vendor bill under standing agreement",
            "modify",
            "Bill lines need reclassification to correct accounts",
            "Reclassify lines then resubmit bill approval",
        ),
        (
            "appr_odoo_delivery_exception",
            "odoo",
            "delivery of backordered lines",
            "approve",
            "Customer accepted partial delivery in writing",
            "Validate picking for available quantities",
            "reject",
            "Customer requires complete delivery only",
            "Hold picking until remaining quantities arrive",
        ),
        (
            "appr_odoo_project_budget",
            "odoo",
            "project budget overrun request",
            "approve",
            "Overrun is funded by change order already signed",
            "Increase project budget to change-order amount",
            "reject",
            "No funded change order supports the overrun",
            "Deny budget increase and keep original ceiling",
        ),
        (
            "appr_odoo_sign_contract",
            "odoo",
            "customer contract Sign send",
            "approve",
            "Contract terms match negotiated commercial terms",
            "Send Sign request to customer contacts",
            "modify",
            "Payment schedule clause needs corrected milestones",
            "Update payment schedule then resend for approval",
        ),
        (
            "appr_odoo_loyalty_override",
            "odoo",
            "loyalty points manual adjustment",
            "approve",
            "Adjustment matches documented customer goodwill case",
            "Apply loyalty points adjustment",
            "reject",
            "Adjustment lacks documented goodwill justification",
            "Deny points adjustment and keep balance unchanged",
        ),
        (
            "appr_odoo_warehouse_transfer",
            "odoo",
            "inter-warehouse emergency transfer",
            "approve",
            "Receiving warehouse confirms capacity and urgency",
            "Validate inter-warehouse transfer",
            "modify",
            "Requested quantity exceeds receiving capacity; reduce qty",
            "Lower transfer quantity then resubmit",
        ),
        (
            "appr_odoo_fiscal_close",
            "odoo",
            "fiscal period close",
            "approve",
            "All required journals are reviewed and balanced",
            "Close fiscal period for the company",
            "reject",
            "Open draft moves remain in the period",
            "Keep period open until drafts are cleared",
        ),
        (
            "appr_odoo_asset_dispose",
            "odoo",
            "fixed asset disposal",
            "approve",
            "Disposal proceeds and residual value are reconciled",
            "Post asset disposal entry",
            "modify",
            "Disposal date must match physical decommission date",
            "Correct disposal date then resubmit",
        ),
        (
            "appr_odoo_recruit_offer",
            "odoo",
            "recruitment offer letter",
            "approve",
            "Compensation is within band and headcount plan",
            "Send offer letter to candidate",
            "reject",
            "Compensation exceeds approved band without exception",
            "Return offer for band-compliant compensation",
        ),
        (
            "appr_odoo_portal_user",
            "odoo",
            "external portal user invitation",
            "approve",
            "Invitee is an authorized partner contact",
            "Send portal invitation with scoped access",
            "reject",
            "Invitee email is not on the partner contact list",
            "Deny invitation until contact is registered",
        ),
        (
            "appr_odoo_tax_lock",
            "odoo",
            "tax lock date advance",
            "approve",
            "Tax returns for prior period are filed and archived",
            "Advance tax lock date to requested day",
            "modify",
            "Advance only through last filed return month",
            "Set lock date to last filed month then confirm",
        ),
        (
            "appr_odoo_dropship",
            "odoo",
            "dropship purchase confirmation",
            "approve",
            "Customer ship-to and vendor lead time are confirmed",
            "Confirm dropship purchase order",
            "reject",
            "Ship-to address conflicts with customer delivery address",
            "Return dropship PO for address correction",
        ),
        (
            "appr_odoo_subscription_cancel",
            "odoo",
            "subscription early cancellation",
            "approve",
            "Cancellation terms and proration match contract",
            "Cancel subscription with approved proration",
            "modify",
            "End date must align with billing period boundary",
            "Adjust cancellation end date then resubmit",
        ),
        (
            "appr_odoo_quality_alert",
            "odoo",
            "quality alert release to production",
            "approve",
            "Containment actions completed and verified",
            "Release quality alert and resume production",
            "reject",
            "Containment incomplete for affected lots",
            "Keep production blocked until containment finishes",
        ),
        (
            "appr_odoo_landed_cost",
            "odoo",
            "landed cost allocation",
            "approve",
            "Allocation keys match shipment cost documents",
            "Post landed cost to inventory valuation",
            "modify",
            "Freight share should use weight not quantity",
            "Switch allocation key to weight then resubmit",
        ),
        (
            "appr_odoo_commission",
            "odoo",
            "sales commission exception",
            "approve",
            "Exception is pre-approved in the sales plan",
            "Post commission with exception rate",
            "reject",
            "Exception rate not present in approved sales plan",
            "Deny exception and use standard commission rate",
        ),
        (
            "appr_odoo_repair_order",
            "odoo",
            "warranty repair cost overrun",
            "approve",
            "Overrun covered by extended warranty clause",
            "Authorize additional repair cost under warranty",
            "modify",
            "Customer must approve non-warranty portion first",
            "Split warranty vs billable lines then resubmit",
        ),
        # --- Generic ---
        (
            "appr_gen_prod_deploy",
            None,
            "production deploy of release candidate",
            "approve",
            "Change ticket, tests, and rollback plan are complete",
            "Proceed with production deploy",
            "reject",
            "Rollback plan is missing for a high-risk change",
            "Block deploy until rollback plan is attached",
        ),
        (
            "appr_gen_schema_migration",
            None,
            "breaking schema migration",
            "approve",
            "Dual-write window and backfill plan are verified",
            "Allow schema migration in the maintenance window",
            "modify",
            "Backfill must finish before cutover flip",
            "Reorder steps so backfill precedes cutover",
        ),
        (
            "appr_gen_secret_rotation",
            None,
            "production secret rotation",
            "approve",
            "Dual-key overlap window is scheduled and monitored",
            "Rotate production secrets under overlap window",
            "reject",
            "No dual-key overlap configured for rotation",
            "Deny rotation until overlap is configured",
        ),
        (
            "appr_gen_data_export",
            None,
            "bulk customer data export",
            "approve",
            "Requester has lawful basis and scoped fields only",
            "Allow scoped bulk export to secure destination",
            "reject",
            "Export requests fields outside permitted scope",
            "Deny export until field list is reduced",
        ),
        (
            "appr_gen_firewall_change",
            None,
            "ingress firewall rule change",
            "approve",
            "Source ranges are least-privilege and time-bounded",
            "Apply temporary ingress firewall rule",
            "modify",
            "Narrow source CIDR and shorten expiry",
            "Resubmit rule with tighter CIDR and expiry",
        ),
        (
            "appr_gen_feature_flag",
            None,
            "global feature-flag enablement",
            "approve",
            "Canary metrics meet success criteria for full rollout",
            "Enable feature flag for all tenants",
            "modify",
            "Hold at 25% cohort until error rate improves",
            "Cap rollout percentage then re-review",
        ),
        (
            "appr_gen_vendor_contract",
            None,
            "third-party vendor contract",
            "approve",
            "Legal and security reviews are signed off",
            "Execute vendor contract",
            "reject",
            "Security review open items remain unresolved",
            "Hold contract until security items close",
        ),
        (
            "appr_gen_pii_access",
            None,
            "elevated PII datastore access",
            "approve",
            "Access is ticketed, time-boxed, and audited",
            "Grant temporary PII datastore access",
            "reject",
            "Request lacks ticketed business justification",
            "Deny PII access until justification is filed",
        ),
        (
            "appr_gen_rate_limit_raise",
            None,
            "API rate-limit increase",
            "approve",
            "Capacity and abuse controls support the new limit",
            "Raise API rate limit for the named client",
            "modify",
            "Increase is acceptable only during business hours",
            "Apply limit raise with daytime schedule only",
        ),
        (
            "appr_gen_incident_page",
            None,
            "customer-facing incident page publish",
            "approve",
            "Status text is accurate and omits sensitive internals",
            "Publish customer-facing incident update",
            "modify",
            "Remove internal hostnames from the status text",
            "Edit status text then resubmit publish approval",
        ),
        (
            "appr_gen_backup_restore",
            None,
            "production backup restore drill",
            "approve",
            "Restore target is isolated and data-handling approved",
            "Run production backup restore in isolated target",
            "reject",
            "Restore target is not isolated from production traffic",
            "Deny restore until isolation is confirmed",
        ),
        (
            "appr_gen_model_prompt",
            None,
            "system prompt change for assistant",
            "approve",
            "Prompt change is reviewed for safety and policy fit",
            "Deploy updated system prompt",
            "modify",
            "Add explicit refusal language for disallowed topics",
            "Amend prompt with refusal language then resubmit",
        ),
        (
            "appr_gen_cost_budget",
            None,
            "cloud spend budget increase",
            "approve",
            "Increase is funded and tied to capacity plan",
            "Raise cloud spend budget for the service",
            "reject",
            "Increase lacks funded capacity justification",
            "Keep current budget until funding is confirmed",
        ),
        (
            "appr_gen_dns_cutover",
            None,
            "DNS cutover to new edge",
            "approve",
            "Health checks pass and TTL drain plan is ready",
            "Proceed with DNS cutover",
            "modify",
            "Lower TTL for a longer soak before cutover",
            "Extend TTL soak window then resubmit",
        ),
        (
            "appr_gen_delete_tenant",
            None,
            "tenant hard-delete request",
            "approve",
            "Retention window elapsed and legal hold is clear",
            "Hard-delete tenant data after retention clearance",
            "reject",
            "Legal hold is still active for the tenant",
            "Deny hard-delete while legal hold remains",
        ),
        (
            "appr_gen_hotfix",
            None,
            "out-of-band hotfix merge",
            "approve",
            "Hotfix is minimal, tested, and severity justifies bypass",
            "Merge hotfix to release line",
            "modify",
            "Scope must exclude unrelated refactors in the same PR",
            "Strip unrelated commits then resubmit hotfix",
        ),
        (
            "appr_gen_s3_public",
            None,
            "temporary public object ACL",
            "approve",
            "Public ACL is time-boxed and contains non-sensitive assets",
            "Allow temporary public ACL with auto-expiry",
            "reject",
            "Object set includes sensitive documents",
            "Deny public ACL for sensitive object set",
        ),
        (
            "appr_gen_oncall_override",
            None,
            "on-call escalation policy override",
            "approve",
            "Override covers known staffing gap with backup coverage",
            "Apply temporary on-call escalation override",
            "modify",
            "Shorten override window and name backup responder",
            "Tighten override window with named backup",
        ),
        (
            "appr_gen_ml_dataset",
            None,
            "training dataset publish",
            "approve",
            "Dataset licensing and PII scrubbing checks passed",
            "Publish training dataset to internal catalog",
            "reject",
            "PII scrubbing report is incomplete",
            "Hold publish until scrubbing report is complete",
        ),
        (
            "appr_gen_partner_api_key",
            None,
            "partner production API key issue",
            "approve",
            "Partner contract and scopes are verified",
            "Issue production API key with contracted scopes",
            "modify",
            "Remove write scopes not included in the contract",
            "Issue key after removing uncontracted write scopes",
        ),
        (
            "appr_gen_log_retention",
            None,
            "extend log retention beyond policy",
            "approve",
            "Extension is legally required and time-bounded",
            "Extend log retention for the named systems",
            "reject",
            "Extension request lacks legal requirement evidence",
            "Keep standard retention without extension",
        ),
        (
            "appr_gen_canary_abort",
            None,
            "abort canary and roll back",
            "approve",
            "Error budget burn justifies immediate abort",
            "Abort canary and roll back to prior version",
            "modify",
            "Pause canary instead of full abort while investigating",
            "Pause canary traffic share pending investigation",
        ),
        (
            "appr_gen_docs_publish",
            None,
            "external API docs publish",
            "approve",
            "Docs match GA endpoints and omit internal routes",
            "Publish external API documentation",
            "modify",
            "Remove undocumented beta endpoints from the docs",
            "Strip beta endpoints then resubmit docs",
        ),
        (
            "appr_gen_quota_exception",
            None,
            "tenant quota exception",
            "approve",
            "Exception is temporary and commercially approved",
            "Raise tenant quota for the approved window",
            "reject",
            "Exception would starve neighboring tenants",
            "Deny quota exception under current capacity",
        ),
        (
            "appr_gen_certificate",
            None,
            "custom TLS certificate install",
            "approve",
            "Certificate chain and ownership are validated",
            "Install custom TLS certificate on the edge",
            "modify",
            "Intermediate certificate is missing from the chain",
            "Complete chain then resubmit certificate install",
        ),
        (
            "appr_gen_research_access",
            None,
            "offline research copy of production sample",
            "approve",
            "Sample is anonymized and covered by research agreement",
            "Provide anonymized research sample",
            "reject",
            "Sample is not anonymized to research agreement standard",
            "Deny research copy until anonymization is proven",
        ),
        (
            "appr_odoo_multi_company_invoice",
            "odoo",
            "inter-company invoice posting",
            "approve",
            "Inter-company mapping and taxes are consistent",
            "Post inter-company invoice pair",
            "modify",
            "Align invoice dates across companies before posting",
            "Synchronize dates then resubmit posting approval",
        ),
        (
            "appr_odoo_payment_token",
            "odoo",
            "store customer payment token",
            "approve",
            "Customer consent and PCI scope checks passed",
            "Store payment token for future charges",
            "reject",
            "Customer consent for token storage is missing",
            "Deny token storage until consent is recorded",
        ),
        (
            "appr_gen_region_failover",
            None,
            "manual region failover",
            "approve",
            "Primary region health is below SLO with confirmed impact",
            "Execute manual failover to secondary region",
            "modify",
            "Fail over read traffic only before writes",
            "Limit initial failover to reads then reassess",
        ),
        (
            "appr_gen_support_impersonation",
            None,
            "support agent impersonation session",
            "approve",
            "Customer ticket authorizes time-boxed impersonation",
            "Allow support impersonation for the ticket window",
            "reject",
            "Ticket does not authorize account impersonation",
            "Deny impersonation without customer authorization",
        ),
        (
            "appr_odoo_mass_mailing",
            "odoo",
            "mass mailing campaign send",
            "approve",
            "Audience opt-in and content compliance checks passed",
            "Send mass mailing campaign",
            "modify",
            "Exclude recently unsubscribed segments before send",
            "Refresh suppression list then resubmit send approval",
        ),
        (
            "appr_gen_dependency_bump",
            None,
            "major dependency version bump",
            "approve",
            "Compatibility tests and security advisories are clear",
            "Merge major dependency bump",
            "reject",
            "Known CVE remains open on the target version",
            "Block bump until CVE is addressed",
        ),
        (
            "appr_odoo_inventory_adjust",
            "odoo",
            "cycle count inventory adjustment",
            "approve",
            "Count variance is within tolerance with recount evidence",
            "Post inventory adjustment from cycle count",
            "modify",
            "Recount one SKU before posting the adjustment",
            "Recount flagged SKU then resubmit adjustment",
        ),
        (
            "appr_gen_webhook_endpoint",
            None,
            "register partner webhook endpoint",
            "approve",
            "Endpoint ownership and signing secret are verified",
            "Register partner webhook endpoint",
            "reject",
            "Endpoint fails challenge verification",
            "Deny registration until challenge succeeds",
        ),
        (
            "appr_odoo_analytic_override",
            "odoo",
            "analytic distribution override",
            "approve",
            "Override matches project funding split documentation",
            "Apply analytic distribution override",
            "modify",
            "Percentages must sum to 100 before apply",
            "Fix distribution percentages then resubmit",
        ),
        (
            "appr_gen_emergency_acl",
            None,
            "emergency break-glass ACL",
            "approve",
            "Severity warrants break-glass with recorded incident id",
            "Grant emergency ACL with automatic expiry",
            "reject",
            "No active incident id linked to break-glass request",
            "Deny emergency ACL without incident linkage",
        ),
        (
            "appr_odoo_consignment",
            "odoo",
            "consignment stock ownership transfer",
            "approve",
            "Ownership transfer terms match consignment contract",
            "Transfer consignment ownership in inventory",
            "modify",
            "Transfer only consumed quantities, not full stock",
            "Limit transfer to consumed qty then resubmit",
        ),
        (
            "appr_gen_dataset_delete",
            None,
            "delete obsolete analytics dataset",
            "approve",
            "No downstream jobs depend on the dataset",
            "Delete obsolete analytics dataset",
            "reject",
            "Active scheduled jobs still read the dataset",
            "Keep dataset until dependent jobs are retired",
        ),
        (
            "appr_odoo_rma",
            "odoo",
            "customer RMA beyond return window",
            "approve",
            "Goodwill exception authorized by account manager",
            "Create RMA beyond standard return window",
            "reject",
            "No goodwill authorization for late RMA",
            "Deny late RMA under standard return policy",
        ),
        (
            "appr_gen_capacity_scale",
            None,
            "emergency capacity scale-out",
            "approve",
            "Load metrics exceed scale trigger with headroom plan",
            "Scale out capacity to the approved replica count",
            "modify",
            "Scale in smaller increments with observation pauses",
            "Apply stepwise scale-out then reassess",
        ),
        (
            "appr_odoo_landed_customs",
            "odoo",
            "customs duty landed cost",
            "approve",
            "Customs documents match shipment and duty amount",
            "Post customs duty as landed cost",
            "reject",
            "Duty amount conflicts with customs declaration",
            "Hold posting until declaration amount is reconciled",
        ),
        (
            "appr_gen_audit_export",
            None,
            "external auditor log export",
            "approve",
            "Export is scoped to audit period and NDA is in place",
            "Provide auditor log export for the scoped period",
            "modify",
            "Narrow export to systems listed in the audit letter",
            "Limit systems then resubmit auditor export",
        ),
        (
            "appr_odoo_partner_merge",
            "odoo",
            "duplicate partner merge",
            "approve",
            "Surviving partner and field precedence are confirmed",
            "Merge duplicate partners into surviving record",
            "modify",
            "Preserve fiscal address from the secondary partner",
            "Adjust field precedence then resubmit merge",
        ),
        (
            "appr_gen_cdn_purge",
            None,
            "global CDN cache purge",
            "approve",
            "Purge is required after incorrect asset publish",
            "Purge global CDN cache for affected paths",
            "reject",
            "Path pattern is too broad and risks collateral purge",
            "Deny purge until path pattern is narrowed",
        ),
        (
            "appr_odoo_payroll_run",
            "odoo",
            "payroll batch confirmation",
            "approve",
            "Payroll variance report is within tolerance",
            "Confirm payroll batch for payment",
            "modify",
            "Exclude one employee with unresolved timesheet dispute",
            "Remove disputed employee then resubmit payroll",
        ),
        (
            "appr_gen_sla_credit",
            None,
            "customer SLA credit issuance",
            "approve",
            "SLA breach and credit formula match the contract",
            "Issue SLA credit to customer account",
            "reject",
            "Breach window is outside contracted measurement",
            "Deny credit outside measurement window",
        ),
        (
            "appr_odoo_gift_card",
            "odoo",
            "high-value gift card issuance",
            "approve",
            "Issuance is funded and fraud checks passed",
            "Issue high-value gift card",
            "modify",
            "Lower face value to funded amount only",
            "Reduce face value then resubmit issuance",
        ),
        (
            "appr_gen_mirror_sync",
            None,
            "force mirror sync from primary",
            "approve",
            "Primary checksum and maintenance window are confirmed",
            "Force mirror sync from primary to replicas",
            "reject",
            "Maintenance window has not started",
            "Delay force sync until maintenance window opens",
        ),
        (
            "appr_odoo_kit_delivery",
            "odoo",
            "deliver incomplete product kit",
            "approve",
            "Customer accepted incomplete kit delivery in writing",
            "Deliver available kit components now",
            "reject",
            "Customer requires complete kit only",
            "Hold delivery until all kit components are available",
        ),
        (
            "appr_gen_beta_invite",
            None,
            "expand private beta invite list",
            "approve",
            "Invitees match beta cohort criteria and NDA status",
            "Expand private beta invite list",
            "modify",
            "Remove invitees lacking signed NDA",
            "Filter to NDA-complete invitees then resubmit",
        ),
        (
            "appr_odoo_downpayment",
            "odoo",
            "sales downpayment invoice",
            "approve",
            "Downpayment percent matches signed quotation terms",
            "Create and confirm downpayment invoice",
            "reject",
            "Downpayment percent exceeds quotation terms",
            "Deny downpayment until percent matches quotation",
        ),
    ]
    out: list[_ApprFamily] = []
    for (
        slug,
        domain,
        subject,
        kind_a,
        reason_a,
        next_a,
        kind_b,
        reason_b,
        next_b,
    ) in specs:
        assert kind_a in _APPROVAL_KINDS and kind_b in _APPROVAL_KINDS
        assert kind_a != kind_b
        out.append(
            _ApprFamily(
                family_id=slug,
                domain=domain,
                subject=subject,
                kind_a=kind_a,
                reason_a=reason_a,
                next_a=next_a,
                kind_b=kind_b,
                reason_b=reason_b,
                next_b=next_b,
            )
        )
    return tuple(out)


def _extra(family: _ApprFamily, role: str, kind: str) -> dict[str, Any]:
    return {
        "reasoning_sparse_version": REASONING_SPARSE_VERSION,
        "scenario_family": family.family_id,
        "approval_role": role,
        "approval_subject": family.subject,
        "approval_kind": kind,
        "fp2_native": True,
        "legacy": False,
        "controlled_approval": True,
    }


def _make_ld(
    *,
    index: int,
    family: _ApprFamily,
    role: str,
    kind: str,
    reason: str,
    next_goal: str,
) -> dict[str, Any]:
    rec = LoopDecisionRecord(
        record_type="loop_decision",
        record_id=rid("appr-ld", index),
        decision_kind=kind,
        reason=f"[{family.family_id}] {reason}",
        next_goal=next_goal,
        provider_capability="approval",
        domain_specialization=family.domain,
        metadata=fixture_metadata(
            generator=APPROVAL_CONTROLLED_GENERATOR,
            index=index,
            provider_capability="approval",
            domain_specialization=family.domain,
            extra=_extra(family, role, kind),
        ),
    )
    return rec.to_dict()


def generate_approval_controlled_records() -> list[dict[str, Any]]:
    """Generate controlled Approval corpus (~160–200), deterministic, family-linked."""
    records: list[dict[str, Any]] = []
    ld_i = 0
    families = _families()
    if len(families) < MIN_FAMILIES:
        raise RuntimeError(f"approval families {len(families)} < {MIN_FAMILIES}")

    for family in families:
        ld_i += 1
        records.append(
            _make_ld(
                index=ld_i,
                family=family,
                role="loop_primary",
                kind=family.kind_a,
                reason=family.reason_a,
                next_goal=family.next_a,
            )
        )
        ld_i += 1
        records.append(
            _make_ld(
                index=ld_i,
                family=family,
                role="loop_alternate",
                kind=family.kind_b,
                reason=family.reason_b,
                next_goal=family.next_b,
            )
        )

    seen_fp: set[str] = set()
    deduped: list[dict[str, Any]] = []
    for rec in records:
        validate_record_mapping(rec)
        assert rec["provider_capability"] == "approval"
        assert rec["record_type"] == "loop_decision"
        assert rec["training_contract_version"] == SYSTEM_TRAINING_CONTRACT_VERSION
        assert rec["metadata"].get("scenario_family")
        assert rec["metadata"].get("legacy") is False
        kind = rec["expected_output"]["decision_kind"]
        assert kind in _APPROVAL_KINDS
        assert str(rec["expected_output"].get("reason") or "").strip()
        assert not scan_forbidden_how(rec)
        assert not scan_taxonomy(rec)
        fp = fingerprint_record(rec)
        if fp in seen_fp:
            continue
        seen_fp.add(fp)
        deduped.append(rec)

    if not (TARGET_MIN <= len(deduped) <= TARGET_MAX):
        raise RuntimeError(
            f"controlled Approval count {len(deduped)} outside [{TARGET_MIN}, {TARGET_MAX}]"
        )
    return deduped


def approval_family_count() -> int:
    return len(_families())
