"""Immutable domain models for aiodoo-training."""

from aiodoo_training.domain.artifacts import (
    EvaluationReport,
    ExperimentManifest,
    ExportArtifact,
)
from aiodoo_training.domain.checkpoint_manifest import CheckpointManifest, CheckpointMetadata
from aiodoo_training.domain.config import (
    AdaptationSpec,
    CheckpointingSpec,
    CurriculumSpec,
    DatasetMixSpec,
    DeterminismSpec,
    DistributedSpec,
    EvaluationSpec,
    ExecutionSpec,
    ExperimentConfig,
    ExportSpec,
    OptimizationSpec,
    PackingSpec,
    PrecisionSpec,
    TrackingSpec,
)
from aiodoo_training.domain.curriculum_session import (
    CurriculumProgress,
    CurriculumSession,
    CurriculumState,
    CurriculumStatistics,
)
from aiodoo_training.domain.enums import (
    AcceleratorKind,
    AdapterType,
    CheckpointType,
    ComparisonOp,
    CurriculumMode,
    CurriculumStatus,
    DatasetSplitKind,
    DatasetType,
    DeviceKind,
    EvaluationStatus,
    ExportStatus,
    ExportType,
    ModelFamily,
    PackingMode,
    PackingOverflow,
    PackingStatus,
    PipelineStage,
    Precision,
    StageStatus,
    TrackerType,
    TrainingBackend,
    TrainingStatus,
)
from aiodoo_training.domain.evaluation_policies import (
    AcceptancePolicy,
    EvaluationPolicy,
    EvaluationProfile,
    ExportProfile,
    QualityThreshold,
    ThresholdCombine,
    ThresholdSeverity,
)
from aiodoo_training.domain.evaluation_session import (
    EvaluationProgress,
    EvaluationSession,
    EvaluationState,
)
from aiodoo_training.domain.examples import (
    IGNORE_INDEX,
    TokenBatch,
    TokenizationConfig,
    TrainingExample,
)
from aiodoo_training.domain.export_manifest import (
    ARTIFACT_PROTOCOL_VERSION,
    ArtifactBundle,
    ArtifactCompatibilityPolicy,
    ArtifactDescriptor,
    ArtifactIndexEntry,
    ArtifactValidationPolicy,
    ExportManifest,
    compute_export_fingerprint,
)
from aiodoo_training.domain.export_session import ExportSession, ExportState
from aiodoo_training.domain.handles import BaseModelHandle, TrainableModelHandle
from aiodoo_training.domain.identifiers import ExperimentId, RunId, StageName
from aiodoo_training.domain.metric_definition import MetricAggregation, MetricDefinition
from aiodoo_training.domain.packing_policies import (
    MemoryPackingPolicy,
    PackingPolicy,
    SamplingSpec,
)
from aiodoo_training.domain.packing_session import (
    PackedSpan,
    PackingProgress,
    PackingSession,
    PackingState,
    PackingStatistics,
)
from aiodoo_training.domain.pipeline import PipelineResult, StageResult
from aiodoo_training.domain.quality import QualityFailure, QualityReport
from aiodoo_training.domain.refs import AdapterRef, DatasetRef, ModelRef
from aiodoo_training.domain.resources import (
    DevicePolicy,
    ExecutionEnvironment,
    HardwareCapabilities,
    MemoryPolicy,
    PrecisionPolicy,
)
from aiodoo_training.domain.session import DatasetSession
from aiodoo_training.domain.training import CheckpointHandle, MetricSnapshot, TrainingProgress
from aiodoo_training.domain.training_events import TrainerResult, TrainingEvent, TrainingEventKind
from aiodoo_training.domain.training_policies import (
    TRAINING_PROTOCOL_VERSION,
    CheckpointPolicy,
    GradientAccumulationPolicy,
    GradientClippingPolicy,
    LossScalingPolicy,
    MixedPrecisionPolicy,
    OptimizerPolicy,
    ResumePolicy,
    SchedulerPolicy,
)
from aiodoo_training.domain.training_session import TrainingSession, TrainingState

__all__ = [
    "ARTIFACT_PROTOCOL_VERSION",
    "AcceptancePolicy",
    "AcceleratorKind",
    "AdaptationSpec",
    "AdapterRef",
    "AdapterType",
    "ArtifactBundle",
    "ArtifactCompatibilityPolicy",
    "ArtifactDescriptor",
    "ArtifactIndexEntry",
    "ArtifactValidationPolicy",
    "BaseModelHandle",
    "CheckpointHandle",
    "CheckpointType",
    "CheckpointingSpec",
    "ComparisonOp",
    "CurriculumMode",
    "CurriculumProgress",
    "CurriculumSession",
    "CurriculumSpec",
    "CurriculumState",
    "CurriculumStatistics",
    "CurriculumStatus",
    "DatasetMixSpec",
    "DatasetRef",
    "DatasetSession",
    "DatasetSplitKind",
    "DatasetType",
    "DeterminismSpec",
    "DeviceKind",
    "DevicePolicy",
    "DistributedSpec",
    "EvaluationPolicy",
    "EvaluationProfile",
    "EvaluationProgress",
    "EvaluationReport",
    "EvaluationSession",
    "EvaluationSpec",
    "EvaluationState",
    "ExportProfile",
    "EvaluationStatus",
    "ExecutionEnvironment",
    "ExecutionSpec",
    "ExperimentConfig",
    "ExperimentId",
    "ExperimentManifest",
    "ExportArtifact",
    "ExportManifest",
    "ExportSession",
    "ExportSpec",
    "ExportState",
    "ExportStatus",
    "ExportType",
    "HardwareCapabilities",
    "IGNORE_INDEX",
    "MemoryPackingPolicy",
    "MemoryPolicy",
    "MetricAggregation",
    "MetricDefinition",
    "MetricSnapshot",
    "ModelFamily",
    "ModelRef",
    "OptimizationSpec",
    "PackedSpan",
    "PackingMode",
    "PackingOverflow",
    "PackingPolicy",
    "PackingProgress",
    "PackingSession",
    "PackingSpec",
    "PackingState",
    "PackingStatistics",
    "PackingStatus",
    "PipelineResult",
    "SamplingSpec",
    "PipelineStage",
    "Precision",
    "PrecisionPolicy",
    "PrecisionSpec",
    "QualityFailure",
    "QualityReport",
    "QualityThreshold",
    "RunId",
    "StageName",
    "StageResult",
    "StageStatus",
    "ThresholdCombine",
    "ThresholdSeverity",
    "TokenBatch",
    "TokenizationConfig",
    "TrackerType",
    "TrackingSpec",
    "TrainableModelHandle",
    "TRAINING_PROTOCOL_VERSION",
    "TrainerResult",
    "TrainingBackend",
    "TrainingEvent",
    "TrainingEventKind",
    "TrainingExample",
    "TrainingProgress",
    "TrainingSession",
    "TrainingState",
    "TrainingStatus",
    "CheckpointManifest",
    "CheckpointMetadata",
    "CheckpointPolicy",
    "GradientAccumulationPolicy",
    "GradientClippingPolicy",
    "LossScalingPolicy",
    "MixedPrecisionPolicy",
    "OptimizerPolicy",
    "ResumePolicy",
    "SchedulerPolicy",
    "compute_export_fingerprint",
]
